/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author gabri
 */
public class ProductionPlan extends javax.swing.JFrame {

    /**
     * Creates new form ProductionPlan
     */
    public ProductionPlan() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size= toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2-getHeight()/2);
        currentDate();
        //startTableShift();
    }
   public void currentDate(){
        Calendar cal= new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year= cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
       
        jLabel7.setText(day+"/"+(month+1)+"/" + year);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 429));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/340.png"))); // NOI18N
        jButton1.setText("Close Window");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 340, 229, 32);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel5.setText("Production Plan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 30, 370, 43);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/png-clipart-computer-icons-calendar-date-calendrier-text-calendar.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(620, 50, 100, 16);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Day 1 Orders", "Day 2 Orders", "Day 3 Orders", "Day 4 Orders", "Day 5 Orders"
            }
        ));
        jTable5.setGridColor(new java.awt.Color(0, 0, 0));
        jTable5.setRowHeight(25);
        jTable5.setShowGrid(true);
        jScrollPane5.setViewportView(jTable5);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(150, 100, 452, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/colorkit (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void startTableShift() {
        Timer timer = new Timer(60000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                shiftTable();
            }
        });
        timer.start();
    }

    private void shiftTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable5.getModel();
        int columnCount = model.getColumnCount();
        int rowCount = model.getRowCount();
        Object[][] newData = new Object[rowCount][columnCount];
        String[] newColumnNames = new String[columnCount];

        // Shift data and column names
        for (int i = 0; i < columnCount - 1; i++) {
            newColumnNames[i] = model.getColumnName(i + 1);
            for (int j = 0; j < rowCount; j++) {
                newData[j][i] = model.getValueAt(j, i + 1);
            }
        }

        // Parse day number from last column's name
        String lastColumnName = model.getColumnName(columnCount - 1);
        int lastDayNumber = Integer.parseInt(lastColumnName.split(" ")[1]);

        // Add new column
        newColumnNames[columnCount - 1] = "Day " + (lastDayNumber + 1) + " Orders";
        for (int j = 0; j < rowCount; j++) {
            newData[j][columnCount - 1] = null;
        }

        // Set new model
        model.setDataVector(newData, newColumnNames);
    }

    public void updateTableDay(int day, int orderNumber) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable5.getModel();
        for(int columnIndex = 0; columnIndex < model.getColumnCount(); columnIndex++) {
            String currentDay = model.getColumnName(columnIndex);
            if(currentDay.equals("Day " + day + " Orders")) {
                for(int i = 0; i < model.getRowCount(); i++) {
                    if(model.getValueAt(i, columnIndex) == null){
                        model.setValueAt(orderNumber, i, columnIndex);
                        break;
                    }
                }
                return;
            }
        }
        System.out.println("Error: Day " + day + " is not currently shown in the table.");
    }


        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductionPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductionPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable5;
    // End of variables declaration//GEN-END:variables
}
