/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logic.Order;

import javax.swing.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class PurchasingPlan extends javax.swing.JFrame {

    /**
     * Creates new form PurchasingPlan
     */
    private int lastTableDay = 5;
    private DefaultTableModel model;
    public PurchasingPlan() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size= toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2-getHeight()/2);
        currentDate();

    }
   public void currentDate(){
        Calendar cal= new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year= cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
       
        jLabel7.setText(day+"/"+(month+1)+"/" + year);
    }
    private void addNewDayColumn() {
        lastTableDay++;
        String newColumnName = "Day " + lastTableDay;
        model.addColumn(newColumnName);
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(null, i, model.getColumnCount() - 1);
        }
        jTable1.getColumnModel().getColumn(model.getColumnCount() - 1).setPreferredWidth(80);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel5.setText("Production Plan");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 400));
        setPreferredSize(new java.awt.Dimension(900, 400));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/340.png"))); // NOI18N
        jButton1.setText("Close Window");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 300, 220, 33);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel6.setText("Purchasing Plan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 20, 562, 43);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/png-clipart-computer-icons-calendar-date-calendrier-text-calendar.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(660, 40, 100, 16);

        model = new DefaultTableModel(
            new Object [][] {
                {"A", "P1", null, null, null, null, null},
                {"A", "P2", null, null, null, null, null},
                {"B", "P1", null, null, null, null, null},
                {"B", "P2", null, null, null, null, null},
                {"C", "P1", null, null, null, null, null},
                {"C", "P2", null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Piece", "Day 1", "Day 2", "Day 3", "Day 4", "Day 5"
            }
        );
        jTable1.setModel(model);
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setRowHeight(25);
        jTable1.setShowGrid(true);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setPreferredWidth(100); // Set each column's preferred width
        }


        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 90, 830, 180);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/colorkit (2).png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -20, 1010, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void updateTable(Order order) {
        String supplier = order.getSupplier()[0].substring(8); // Extract supplier's name from "Supplier X"
        String pieceType = order.getRawPiece();
        int purchasingDay = order.getPurchasingDay();
        int quantity = order.getQuantity();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int columnCount = model.getColumnCount();
        while(purchasingDay >= lastTableDay) {
            addNewDayColumn();
            columnCount++;
        }

        // Check if the purchasing day is present in the column labels
        for (int j = 2; j < columnCount; j++) { // Start from 2 because day columns start from 2
            System.out.println(Integer.parseInt(model.getColumnName(j).substring(4)));
            if (Integer.parseInt(model.getColumnName(j).substring(4)) == purchasingDay) { // Extract day from column name "Day X"
                // If the purchasing day is present, loop through the rows to find the matching supplier and piece type
                System.out.println("its in");
                for (int i = 0; i < model.getRowCount(); i++) {
                    if (model.getValueAt(i, 0).equals(supplier) && model.getValueAt(i, 1).equals(pieceType)) {
                        model.setValueAt(quantity, i, j);
                        System.out.println("Updated table with order: " + supplier + " " + pieceType + " " + quantity + " " + purchasingDay);
                        break;
                    }
                }
                break;
            }
        }
    }



    /**
     * @param args the command line arguments
        */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchasingPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchasingPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchasingPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchasingPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchasingPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
