/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author gabri
 */
public class Sub_MachineStats extends javax.swing.JFrame {

    /**
     * Creates new form Sub_MachineStats
     */
    public Sub_MachineStats() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size= toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2-getHeight()/2);
        currentDate();
    }
public void currentDate(){
        Calendar cal= new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year= cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
       
        jLabel9.setText(day+"/"+(month+1)+"/" + year);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable13 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable14 = new javax.swing.JTable();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable15 = new javax.swing.JTable();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable16 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 605));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 30)); // NOI18N
        jLabel1.setText("Work Pieces Produced By Type");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 10, 520, 36);

        jTable13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", null, null},
                {"5", null, null},
                {"7", null, null},
                {"9", null, null}
            },
            new String [] {
                "Piece Type", "Quantity Produced by Machine Type 1", "Quantity Produced by Machine Type 2"
            }
        ));
        jTable13.setCellSelectionEnabled(true);
        jTable13.setGridColor(new java.awt.Color(0, 0, 0));
        jTable13.setShowGrid(true);
        jScrollPane13.setViewportView(jTable13);

        getContentPane().add(jScrollPane13);
        jScrollPane13.setBounds(690, 390, 640, 90);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", null, null},
                {"4", null, null},
                {"6", null, null},
                {"7", null, null},
                {"8", null, null}
            },
            new String [] {
                "Piece Type", "Quantity Produced by Machine Type 1", "Quantity Produced by Machine Type 2"
            }
        ));
        jTable8.setCellSelectionEnabled(true);
        jTable8.setGridColor(new java.awt.Color(0, 0, 0));
        jTable8.setShowGrid(true);
        jScrollPane8.setViewportView(jTable8);

        getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(20, 220, 640, 110);

        jTable9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", null, null},
                {"5", null, null},
                {"7", null, null},
                {"9", null, null}
            },
            new String [] {
                "Piece Type", "Quantity Produced by Machine Type 3", "Quantity Produced by Machine Type 4"
            }
        ));
        jTable9.setCellSelectionEnabled(true);
        jTable9.setGridColor(new java.awt.Color(0, 0, 0));
        jTable9.setShowGrid(true);
        jScrollPane9.setViewportView(jTable9);

        getContentPane().add(jScrollPane9);
        jScrollPane9.setBounds(690, 90, 640, 110);

        jTable14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", null, null},
                {"4", null, null},
                {"6", null, null},
                {"7", null, null},
                {"8", null, null}
            },
            new String [] {
                "Piece Type", "Quantity Produced by Machine Type 1", "Quantity Produced by Machine Type 2"
            }
        ));
        jTable14.setCellSelectionEnabled(true);
        jTable14.setGridColor(new java.awt.Color(0, 0, 0));
        jTable14.setShowHorizontalLines(true);
        jTable14.setShowVerticalLines(true);
        jScrollPane14.setViewportView(jTable14);

        getContentPane().add(jScrollPane14);
        jScrollPane14.setBounds(20, 70, 640, 110);

        jTable15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", null, null},
                {"4", null, null},
                {"6", null, null},
                {"7", null, null},
                {"8", null, null}
            },
            new String [] {
                "Piece Type", "Quantity Produced by Machine Type 1", "Quantity Produced by Machine Type 2"
            }
        ));
        jTable15.setCellSelectionEnabled(true);
        jTable15.setGridColor(new java.awt.Color(0, 0, 0));
        jTable15.setShowGrid(true);
        jScrollPane15.setViewportView(jTable15);

        getContentPane().add(jScrollPane15);
        jScrollPane15.setBounds(20, 370, 640, 110);

        jTable16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3", null, null},
                {"5", null, null},
                {"7", null, null},
                {"9", null, null}
            },
            new String [] {
                "Piece Type", "Quantity Produced by Machine Type 1", "Quantity Produced by Machine Type 2"
            }
        ));
        jTable16.setCellSelectionEnabled(true);
        jTable16.setGridColor(new java.awt.Color(0, 0, 0));
        jTable16.setShowHorizontalLines(true);
        jTable16.setShowVerticalLines(true);
        jScrollPane16.setViewportView(jTable16);

        getContentPane().add(jScrollPane16);
        jScrollPane16.setBounds(690, 240, 640, 90);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/340.png"))); // NOI18N
        jButton1.setText("Back to Machine Statistics");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(800, 520, 400, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("C1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 40, 37, 40);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("C2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 190, 40, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("C3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 340, 40, 40);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setText("C4");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1000, 70, 40, 21);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("C5");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1000, 180, 60, 100);

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setText("C6");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1000, 370, 50, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/25694.png"))); // NOI18N
        jButton2.setText("Return to Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 520, 400, 40);

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1260, 20, 140, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images2/colorkit2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1380, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        MachineStatistics machinestatistics = new MachineStatistics();
        machinestatistics.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       MainMenu mainmenu = new MainMenu();
        mainmenu.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sub_MachineStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sub_MachineStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sub_MachineStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sub_MachineStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sub_MachineStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable13;
    private javax.swing.JTable jTable14;
    private javax.swing.JTable jTable15;
    private javax.swing.JTable jTable16;
    private javax.swing.JTable jTable8;
    private javax.swing.JTable jTable9;
    // End of variables declaration//GEN-END:variables
}
